################################################################################
# Test file for HTTP route of forgot password
# REST Client for VSCode needed
# https://marketplace.visualstudio.com/items?itemName=humao.rest-client
################################################################################
@endpoint = http://localhost:{{$dotenv PORT}}/forgot-password

### 404
GET {{ endpoint }}/azertyuiop

### Get forgot-password page (only during test)
GET {{ endpoint }}/

### Create link for reset password
POST {{ endpoint }}/
content-type: application/json

{
    "email": "olleks.planning@gmail.com",
}

### Create link for reset password with undefined user
POST {{ endpoint }}/
content-type: application/json

{
    "email": "totom@toto.com"
}

### Create link for reset password with bad email
POST {{ endpoint }}/
content-type: application/json

{
    "email": "withoutarobase.com"
}
