################################################################################
# Test file for HTTP routes of user API
# REST Client for VSCode needed
# https://marketplace.visualstudio.com/items?itemName=humao.rest-client
################################################################################
@endpoint = http://localhost:{{$dotenv PORT}}/api/user

### 404
GET {{ endpoint }}/azertyuiop

### Get one user
GET {{ endpoint }}/1

### Get an user who doesn't exist
GET {{ endpoint }}/9999

### Get an user with an id as not a number
GET {{ endpoint }}/tartempion

### Patch an user 
PATCH {{ endpoint }}/37/profil
content-type: application/json

{
    "phone_number": "0456565656",
    "mobile_number": "0656565656",
    "password": "password"
}

### Patch an user with a bad password
PATCH {{ endpoint }}/37/profil
content-type: application/json

{
    "phone_number": "0456565656",
    "mobile_number": "0656565656",
    "password": "o"
}

### Patch an user with a bad phone number
PATCH {{ endpoint }}/37/profil
content-type: application/json

{
    "phone_number": "045656",
    "mobile_number": "0656565656",
    "password": "password"
}

### Patch an user with a bad mobile number
PATCH {{ endpoint }}/37/profil
content-type: application/json

{
    "phone_number": "0456565656",
    "mobile_number": "06656",
    "password": "password"
}

### Patch an inexistant user
PATCH {{ endpoint }}/999/profil
content-type: application/json

{
    "phone_number": "0456565656",
    "mobile_number": "0656565656",
    "password": "KPP18YZC3OE"
}

### Patch an inexistant user with id as a string
PATCH {{ endpoint }}/tartempion/profil
content-type: application/json

{
    "phone_number": "0456565656",
    "mobile_number": "0656565656",
    "password": "password"
}
